version: '3'
services:

  prisma:
    image: prismagraphql/prisma:1.16.5
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: course-viewer-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  back:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - "./back/database:/app/database"
      - "./back/src:/app/src"

  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - "./front/src:/app/src"
      - "./front/public:/app/public"

volumes:
  postgres:
